option(ENABLE_WERROR "Enable Werror." ON)

function(add_warning_flags TARGET)
    if(NOT MSVC)
        target_compile_options(${TARGET} PRIVATE -Wall -Wextra -Wno-unused-function)
        if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
            target_compile_options(${TARGET} PRIVATE -Wunused-const-variable=1)
        endif()
    else()
        if(ENABLE_WERROR)
            target_compile_options(${TARGET} PRIVATE /W3)
        else()
            target_compile_options(${TARGET} PRIVATE /W4)
        endif()
    endif()
    if(ENABLE_WERROR)
        if(NOT MSVC)
            target_compile_options(${TARGET} PRIVATE -Werror)
        else()
            target_compile_options(${TARGET} PRIVATE /WX)
        endif()
    endif()
endfunction()
